version: "3.8"

services:

#  weather:
#    build: weather_app
#    restart: always
#    volumes:
#      - ./weather_app/statistic:/my_code/statistic

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: yaroslavshyminair@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    networks:
      app_net:
        ipv4_address: 172.19.0.2

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "8080:5432"
    networks:
      app_net:
        ipv4_address: 172.19.0.3
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"
          gateway: 172.19.0.1